In [72]:
import pickle
from ext.jjnp21.automator.analyzer import BasicResultAnalyzer
import numpy as np
import matplotlib as plt

# f = open('/home/jp/Documents/tmp/results.dump', 'rb')
f = open('/home/jp/Documents/tmp/results.dump', 'rb')
results = pickle.load(f)

In [73]:
analyzer = BasicResultAnalyzer(results)
analysis_df = analyzer.basic_kpis()
analysis_df

,name,E2E mean,E2E q50,E2E q75,E2E q90,E2E q99,FET mean,FET q50,FET q75,FET q90,...,tx_time_cl_lb q90,tx_time_cl_lb q99,tx_time_lb_fx mean,tx_time_lb_fx q50,tx_time_lb_fx q75,tx_time_lb_fx q90,tx_time_lb_fx q99,nodes_by_type,total_rq_by_type,avg_rq_by_type
0,LRT 0.05,0.0855,0.0499,0.0666,0.1244,0.8160,0.0227,0.0175,0.0266,0.0274,...,0.0246,0.0654,0.0459,0.0147,0.0200,0.0397,0.7752,"{'rpi3': 11, 'rpi4': 10, 'tx2': 10, 'nuc': 28,...","{'rpi3': 727, 'rpi4': 1130, 'tx2': 5073, 'nuc'...","{'rpi3': 66.0909090909091, 'rpi4': 113.0, 'tx2..."
1,LRT 0.1,0.1038,0.0526,0.0765,0.1602,0.8523,0.0247,0.0175,0.0267,0.0318,...,0.0306,0.0704,0.0608,0.0149,0.0271,0.0514,0.7919,"{'rpi3': 13, 'rpi4': 12, 'tx2': 10, 'nuc': 27,...","{'rpi3': 1075, 'rpi4': 2604, 'tx2': 3621, 'nuc...","{'rpi3': 82.6923076923077, 'rpi4': 217.0, 'tx2..."
2,LRT 0.2,0.0797,0.0495,0.0647,0.1143,0.8078,0.0216,0.0175,0.0266,0.0272,...,0.0273,0.0793,0.0412,0.0139,0.0200,0.0356,0.7725,"{'rpi3': 12, 'rpi4': 6, 'tx2': 10, 'nuc': 27, ...","{'rpi3': 705, 'rpi4': 680, 'tx2': 4462, 'nuc':...","{'rpi3': 58.75, 'rpi4': 113.33333333333333, 't..."
3,LRT 0.3,0.0741,0.0467,0.0580,0.1138,0.8003,0.0218,0.0173,0.0265,0.0271,...,0.0203,0.0707,0.0367,0.0129,0.0181,0.0289,0.7708,"{'rpi3': 11, 'rpi4': 6, 'tx2': 8, 'nuc': 27, '...","{'rpi3': 243, 'rpi4': 425, 'tx2': 3735, 'nuc':...","{'rpi3': 22.09090909090909, 'rpi4': 70.8333333..."
4,LRT 0.4,0.0804,0.0486,0.0623,0.1200,0.8098,0.0238,0.0173,0.0266,0.0274,...,0.0218,0.0706,0.0408,0.0131,0.0189,0.0345,0.7724,"{'rpi3': 9, 'rpi4': 9, 'tx2': 8, 'nuc': 22, 'r...","{'rpi3': 146, 'rpi4': 1464, 'tx2': 4621, 'nuc'...","{'rpi3': 16.22222222222222, 'rpi4': 162.666666..."
5,LRT 0.5,0.0887,0.0456,0.0610,0.1217,0.8260,0.0234,0.0171,0.0266,0.0273,...,0.0200,0.0708,0.0506,0.0130,0.0189,0.0504,0.7749,"{'rpi3': 11, 'rpi4': 9, 'tx2': 9, 'nuc': 22, '...","{'rpi3': 574, 'rpi4': 1077, 'tx2': 5226, 'nuc'...","{'rpi3': 52.18181818181818, 'rpi4': 119.666666..."
6,LRT 0.6,0.0939,0.0466,0.0665,0.1290,0.8069,0.0266,0.0173,0.0266,0.0959,...,0.0200,0.0794,0.0519,0.0121,0.0171,0.0459,0.7722,"{'rpi3': 10, 'rpi4': 5, 'tx2': 6, 'nuc': 21, '...","{'rpi3': 163, 'rpi4': 1211, 'tx2': 3674, 'nuc'...","{'rpi3': 16.3, 'rpi4': 242.2, 'tx2': 612.33333..."
7,LRT 0.7,0.0838,0.0468,0.0633,0.1210,0.7996,0.0255,0.0172,0.0266,0.0501,...,0.0200,0.0792,0.0430,0.0129,0.0179,0.0381,0.7705,"{'rpi3': 7, 'rpi4': 5, 'tx2': 6, 'nuc': 21, 'r...","{'rpi3': 219, 'rpi4': 935, 'tx2': 4558, 'nuc':...","{'rpi3': 31.285714285714285, 'rpi4': 187.0, 't..."
8,LRT 0.8,0.0860,0.0440,0.0644,0.1282,0.8001,0.0273,0.0172,0.0266,0.0961,...,0.0200,0.0807,0.0438,0.0127,0.0154,0.0443,0.7707,"{'rpi3': 8, 'rpi4': 5, 'tx2': 5, 'nuc': 20, 'r...","{'rpi3': 178, 'rpi4': 1330, 'tx2': 5337, 'nuc'...","{'rpi3': 22.25, 'rpi4': 266.0, 'tx2': 1067.4, ..."
9,LRT 0.9,0.0909,0.0459,0.0640,0.1445,0.8033,0.0272,0.0173,0.0267,0.0955,...,0.0199,0.0624,0.0493,0.0131,0.0177,0.0382,0.7709,"{'rpi3': 8, 'rpi4': 10, 'tx2': 8, 'nuc': 20, '...","{'rpi3': 195, 'rpi4': 2627, 'tx2': 5139, 'nuc'...","{'rpi3': 24.375, 'rpi4': 262.7, 'tx2': 642.375..."
10,LRT 1.0,0.0907,0.0482,0.0666,0.1287,0.8025,0.0266,0.0172,0.0267,0.0956,...,0.0202,0.0624,0.0489,0.0131,0.0183,0.0375,0.7718,"{'rpi3': 7, 'rpi4': 6, 'tx2': 9, 'nuc': 21, 'r...","{'rpi3': 29, 'rpi4': 1385, 'tx2': 4263, 'nuc':...","{'rpi3': 4.142857142857143, 'rpi4': 230.833333..."

In [79]:
r = results[10]
invs = r.invocations['t_exec'].resample('5S').quantile(0.75)
print(r.lb_hits['fraction'].mean())
r.lb_hits[r.lb_hits['fraction'] > 0]['fraction'].resample('10S').mean()

0.09785422411739647

time
2021-08-31 19:53:00    0.011078
2021-08-31 19:53:10    0.009839
2021-08-31 19:53:20    0.136334
2021-08-31 19:53:30    0.233983
2021-08-31 19:53:40    0.095533
2021-08-31 19:53:50    0.140593
2021-08-31 19:54:00    0.150521
2021-08-31 19:54:10    0.099163
2021-08-31 19:54:20    0.144253
2021-08-31 19:54:30    0.096580
2021-08-31 19:54:40    0.103076
2021-08-31 19:54:50    0.129577
2021-08-31 19:55:00    0.085691
2021-08-31 19:55:10    0.102100
2021-08-31 19:55:20    0.113283
2021-08-31 19:55:30    0.097545
2021-08-31 19:55:40    0.095983
2021-08-31 19:55:50    0.111999
2021-08-31 19:56:00    0.079171
2021-08-31 19:56:10    0.096381
2021-08-31 19:56:20    0.110901
2021-08-31 19:56:30    0.067505
2021-08-31 19:56:40    0.097379
2021-08-31 19:56:50    0.128618
2021-08-31 19:57:00    0.063873
2021-08-31 19:57:10    0.104873
2021-08-31 19:57:20    0.111402
2021-08-31 19:57:30    0.066683
2021-08-31 19:57:40    0.111608
2021-08-31 19:57:50    0.105236
2021-08-31 19:58:00    0.071380
2021-08-31 19:58:10    0.107242
2021-08-31 19:58:20    0.104198
2021-08-31 19:58:30    0.068996
2021-08-31 19:58:40    0.104430
2021-08-31 19:58:50    0.101616
2021-08-31 19:59:00    0.073356
2021-08-31 19:59:10    0.108683
2021-08-31 19:59:20    0.106332
2021-08-31 19:59:30    0.071797
2021-08-31 19:59:40    0.104084
2021-08-31 19:59:50    0.108943
2021-08-31 20:00:00    0.069046
2021-08-31 20:00:10    0.107277
2021-08-31 20:00:20    0.103107
2021-08-31 20:00:30    0.070951
2021-08-31 20:00:40    0.106118
2021-08-31 20:00:50    0.097943
2021-08-31 20:01:00    0.076204
2021-08-31 20:01:10    0.105936
2021-08-31 20:01:20    0.096210
2021-08-31 20:01:30    0.084504
2021-08-31 20:01:40    0.100469
2021-08-31 20:01:50    0.093675
2021-08-31 20:02:00    0.086603
2021-08-31 20:02:10    0.108556
2021-08-31 20:02:20    0.090186
2021-08-31 20:02:30    0.085558
2021-08-31 20:02:40    0.104822
2021-08-31 20:02:50    0.087095
Freq: 10S, Name: fraction, dtype: float64

In [3]:
import pandas as pd
pd.set_option('display.max_rows', 500)
inv = results[0].invocations
inv.groupby('lb_node').agg('count')
# results[3].function_deployment['node'].unique()

,t_wait,t_exec,t_start,memory,tx_time_cl_lb,tx_time_lb_fx,replica_city,client_city,client_node,function_name,function_image,node,replica_id
lb_node,,,,,,,,,,,,,
xeongpu_9,87538,87538,87538,87538,87538,87538,87538,87538,87538,87538,87538,87538,87538

In [18]:
results[0].invocations.columns

Index(['t_wait', 't_exec', 't_start', 'memory', 'lb_client_latency',
       'lb_function_latency', 'tx_time_cl_lb', 'tx_time_lb_fx', 'replica_city',
       'client_city', 'function_name', 'function_image', 'node', 'replica_id'],
      dtype='object')

In [30]:
from pandas import DataFrame
data = []
for r in results:
    row = {}
    row['name'] = r.experiment.name
    row['total'] = r.invocations['replica_city'].count()
    row['nyc_rep'] = r.invocations[r.invocations['replica_city'] == 'newyork']['replica_city'].count()
    row['nyc_client'] = r.invocations[r.invocations['client_city'] == 'newyork']['client_city'].count()
    row['chg_rep'] = r.invocations[r.invocations['replica_city'] == 'chicago']['replica_city'].count()
    row['chg_client'] = r.invocations[r.invocations['client_city'] == 'chicago']['client_city'].count()
    row['sea_rep'] = r.invocations[r.invocations['replica_city'] == 'seattle']['replica_city'].count()
    row['sea_client'] = r.invocations[r.invocations['client_city'] == 'seattle']['client_city'].count()
    data.append(row)
df = DataFrame(data)

for r in [results[2]]:
    print(r.experiment.name)
    filtered = r.invocations[r.invocations['replica_city'] != r.invocations['client_city']]
    print(filtered)
    print(filtered['replica_city'].count())

df

Round Robin on all nodes
                            t_wait    t_exec  t_start     memory  \
time
2021-06-18 18:59:04.529156     0.0  0.127728   109.58  419430400
2021-06-18 18:59:04.539533     0.0  0.138105   109.58  104857600
2021-06-18 18:59:04.568010     0.0  0.126582   109.62  419430400
2021-06-18 18:59:04.611242     0.0  0.129814   109.66  104857600
2021-06-18 18:59:04.653844     0.0  0.252416   109.58  104857600
...                            ...       ...      ...        ...
2021-06-18 19:09:13.779441     0.0  0.258013   718.70  104857600
2021-06-18 19:09:13.798239     0.0  0.516811   718.46  104857600
2021-06-18 19:09:13.805747     0.0  0.124319   718.86  419430400
2021-06-18 19:09:13.808032     0.0  0.286604   718.70  104857600
2021-06-18 19:09:13.809929     0.0  0.208501   718.78  104857600

                            lb_client_latency  lb_function_latency  \
time
2021-06-18 18:59:04.529156                  0                    0
2021-06-18 18:59:04.539533                  0                    0
2021-06-18 18:59:04.568010                  0                    0
2021-06-18 18:59:04.611242                  0                    0
2021-06-18 18:59:04.653844                  0                    0
...                                       ...                  ...
2021-06-18 19:09:13.779441                  0                    0
2021-06-18 19:09:13.798239                  0                    0
2021-06-18 19:09:13.805747                  0                    0
2021-06-18 19:09:13.808032                  0                    0
2021-06-18 19:09:13.809929                  0                    0

                            tx_time_cl_lb  tx_time_lb_fx replica_city  \
time
2021-06-18 18:59:04.529156       0.011850       0.106210      chicago
2021-06-18 18:59:04.539533       0.020094       0.104568      chicago
2021-06-18 18:59:04.568010       0.011366       0.105660      chicago
2021-06-18 18:59:04.611242       0.011547       0.104456      chicago
2021-06-18 18:59:04.653844       0.010112       0.175173      seattle
...                                   ...            ...          ...
2021-06-18 19:09:13.779441       0.011929       0.239291      seattle
2021-06-18 19:09:13.798239       0.009752       0.104627      newyork
2021-06-18 19:09:13.805747       0.009856       0.104453      newyork
2021-06-18 19:09:13.808032       0.011153       0.106124      chicago
2021-06-18 19:09:13.809929       0.009975       0.104392      newyork

                           client_city        function_name  \
time
2021-06-18 18:59:04.529156     newyork   resnet50-inference
2021-06-18 18:59:04.539533     newyork  mobilenet-inference
2021-06-18 18:59:04.568010     newyork   resnet50-inference
2021-06-18 18:59:04.611242     newyork  mobilenet-inference
2021-06-18 18:59:04.653844     chicago     speech-inference
...                                ...                  ...
2021-06-18 19:09:13.779441     newyork  mobilenet-inference
2021-06-18 19:09:13.798239     chicago     speech-inference
2021-06-18 19:09:13.805747     chicago   resnet50-inference
2021-06-18 19:09:13.808032     newyork     speech-inference
2021-06-18 19:09:13.809929     chicago     speech-inference

                                                       function_image  \
time
2021-06-18 18:59:04.529156        faas-workloads/resnet-inference-gpu
2021-06-18 18:59:04.539533     faas-workloads/mobilenet-inference-tpu
2021-06-18 18:59:04.568010        faas-workloads/resnet-inference-gpu
2021-06-18 18:59:04.611242     faas-workloads/mobilenet-inference-tpu
2021-06-18 18:59:04.653844     faas-workloads/speech-inference-tflite
...                                                               ...
2021-06-18 19:09:13.779441  faas-workloads/mobilenet-inference-tflite
2021-06-18 19:09:13.798239     faas-workloads/speech-inference-tflite
2021-06-18 19:09:13.805747        faas-workloads/resnet-inference-gpu
2021-06-18 19:09:13.808032     faas-workloads/speech-inference-tflite
2021-06-18 19:09:13.809929     faas-workloads/speech-inference-tflite

                                  node       replica_id
time
2021-06-18 18:59:04.529156        nx_0  140049108402704
2021-06-18 18:59:04.539533     coral_1  140049134546512
2021-06-18 18:59:04.568010        nx_0  140049108402704
2021-06-18 18:59:04.611242     coral_1  140049134546512
2021-06-18 18:59:04.653844       nx_16  140049108207120
...                                ...              ...
2021-06-18 19:09:13.779441  xeoncpu_94  140049106642832
2021-06-18 19:09:13.798239     rpi3_77  140049106641360
2021-06-18 19:09:13.805747       tx2_7  140048980545168
2021-06-18 19:09:13.808032      rpi4_0  140049106493904
2021-06-18 19:09:13.809929   rockpi_12  140049106643152

[30996 rows x 14 columns]
30996

,name,total,nyc_rep,nyc_client,chg_rep,chg_client,sea_rep,sea_client
0,Round Robin centralized,45869,13127,19405,16445,13185,16297,13279
1,Least Response Time centralized,45888,5855,19414,39052,13188,981,13286
2,Round Robin on all nodes,45695,12660,19331,16745,13140,16290,13224
3,Least Response Time on all nodes,46002,8123,19470,23690,13218,14189,13314

In [38]:
import pandas as pd
pd.set_option('display.max_rows', 500)
print(results[0].experiment.name)
# results[3].function_deployment['node'].unique()
s = results[3].schedule
s[s['successful'] == True].count()

Round Robin centralized

value            594
function_name    594
image            594
replica_id       594
node_name        594
successful       594
dtype: int64