In [17]:
import pickle
from ext.jjnp21.automator.analyzer import BasicResultAnalyzer

f = open('/home/jp/Documents/tmp/results.dump', 'rb')
results = pickle.load(f)

In [18]:
analyzer = BasicResultAnalyzer(results)
analysis_df = analyzer.basic_kpis()
analysis_df

,name,E2E mean,E2E q50,E2E q75,E2E q90,E2E q99,FET mean,FET q50,FET q75,FET q90,...,tx_time_cl_lb q90,tx_time_cl_lb q99,tx_time_lb_fx mean,tx_time_lb_fx q50,tx_time_lb_fx q75,tx_time_lb_fx q90,tx_time_lb_fx q99,nodes_by_type,total_rq_by_type,avg_rq_by_type
0,Round Robin on all nodes,0.2204,0.2016,0.2803,0.4197,0.6696,0.0796,0.0185,0.0955,0.1699,...,0.0207,0.0621,0.1253,0.1105,0.1906,0.2396,0.2703,"{'rpi3': 32, 'rpi4': 20, 'tx2': 13, 'nuc': 40,...","{'rpi3': 41641, 'rpi4': 24542, 'tx2': 10262, '...","{'rpi3': 1301.28125, 'rpi4': 1227.1, 'tx2': 78..."
1,Least Response Time on all nodes,0.1095,0.0892,0.1408,0.2232,0.3579,0.0387,0.0169,0.0670,0.0933,...,0.0200,0.0613,0.0561,0.0154,0.1047,0.1767,0.2427,"{'rpi3': 28, 'rpi4': 18, 'tx2': 9, 'nuc': 3, '...","{'rpi3': 3325, 'rpi4': 4980, 'tx2': 8349, 'nuc...","{'rpi3': 118.75, 'rpi4': 276.6666666666667, 't..."
2,Round Robin centralized,0.3112,0.3013,0.3866,0.4943,0.7537,0.0793,0.0186,0.0954,0.1698,...,0.1950,0.2229,0.1166,0.1178,0.1855,0.2010,0.2293,"{'rpi3': 32, 'rpi4': 20, 'tx2': 13, 'nuc': 30,...","{'rpi3': 40676, 'rpi4': 25402, 'tx2': 10330, '...","{'rpi3': 1271.125, 'rpi4': 1270.1, 'tx2': 794...."
3,Least Response Time centralized,0.2636,0.2407,0.3339,0.4177,0.7186,0.0603,0.0174,0.0933,0.1297,...,0.1920,0.2212,0.0896,0.0552,0.1457,0.1928,0.2237,"{'rpi3': 32, 'rpi4': 20, 'tx2': 13, 'nuc': 30,...","{'rpi3': 23669, 'rpi4': 21210, 'tx2': 11554, '...","{'rpi3': 739.65625, 'rpi4': 1060.5, 'tx2': 888..."

In [23]:
import pandas as pd
pd.set_option('display.max_rows', 500)
inv = results[2].invocations
inv.groupby('lb_node').agg('count')
# results[3].function_deployment['node'].unique()

,t_wait,t_exec,t_start,memory,lb_client_latency,lb_function_latency,tx_time_cl_lb,tx_time_lb_fx,replica_city,client_city,client_node,function_name,function_image,node,replica_id
lb_node,,,,,,,,,,,,,,,
xeoncpu_19,250004,250004,250004,250004,250004,250004,250004,250004,250004,250004,250004,250004,250004,250004,250004

In [18]:
results[0].invocations.columns

Index(['t_wait', 't_exec', 't_start', 'memory', 'lb_client_latency',
       'lb_function_latency', 'tx_time_cl_lb', 'tx_time_lb_fx', 'replica_city',
       'client_city', 'function_name', 'function_image', 'node', 'replica_id'],
      dtype='object')

In [30]:
from pandas import DataFrame
data = []
for r in results:
    row = {}
    row['name'] = r.experiment.name
    row['total'] = r.invocations['replica_city'].count()
    row['nyc_rep'] = r.invocations[r.invocations['replica_city'] == 'newyork']['replica_city'].count()
    row['nyc_client'] = r.invocations[r.invocations['client_city'] == 'newyork']['client_city'].count()
    row['chg_rep'] = r.invocations[r.invocations['replica_city'] == 'chicago']['replica_city'].count()
    row['chg_client'] = r.invocations[r.invocations['client_city'] == 'chicago']['client_city'].count()
    row['sea_rep'] = r.invocations[r.invocations['replica_city'] == 'seattle']['replica_city'].count()
    row['sea_client'] = r.invocations[r.invocations['client_city'] == 'seattle']['client_city'].count()
    data.append(row)
df = DataFrame(data)

for r in [results[2]]:
    print(r.experiment.name)
    filtered = r.invocations[r.invocations['replica_city'] != r.invocations['client_city']]
    print(filtered)
    print(filtered['replica_city'].count())

df

Round Robin on all nodes
                            t_wait    t_exec  t_start     memory  \
time
2021-06-18 18:59:04.529156     0.0  0.127728   109.58  419430400
2021-06-18 18:59:04.539533     0.0  0.138105   109.58  104857600
2021-06-18 18:59:04.568010     0.0  0.126582   109.62  419430400
2021-06-18 18:59:04.611242     0.0  0.129814   109.66  104857600
2021-06-18 18:59:04.653844     0.0  0.252416   109.58  104857600
...                            ...       ...      ...        ...
2021-06-18 19:09:13.779441     0.0  0.258013   718.70  104857600
2021-06-18 19:09:13.798239     0.0  0.516811   718.46  104857600
2021-06-18 19:09:13.805747     0.0  0.124319   718.86  419430400
2021-06-18 19:09:13.808032     0.0  0.286604   718.70  104857600
2021-06-18 19:09:13.809929     0.0  0.208501   718.78  104857600

                            lb_client_latency  lb_function_latency  \
time
2021-06-18 18:59:04.529156                  0                    0
2021-06-18 18:59:04.539533                  0                    0
2021-06-18 18:59:04.568010                  0                    0
2021-06-18 18:59:04.611242                  0                    0
2021-06-18 18:59:04.653844                  0                    0
...                                       ...                  ...
2021-06-18 19:09:13.779441                  0                    0
2021-06-18 19:09:13.798239                  0                    0
2021-06-18 19:09:13.805747                  0                    0
2021-06-18 19:09:13.808032                  0                    0
2021-06-18 19:09:13.809929                  0                    0

                            tx_time_cl_lb  tx_time_lb_fx replica_city  \
time
2021-06-18 18:59:04.529156       0.011850       0.106210      chicago
2021-06-18 18:59:04.539533       0.020094       0.104568      chicago
2021-06-18 18:59:04.568010       0.011366       0.105660      chicago
2021-06-18 18:59:04.611242       0.011547       0.104456      chicago
2021-06-18 18:59:04.653844       0.010112       0.175173      seattle
...                                   ...            ...          ...
2021-06-18 19:09:13.779441       0.011929       0.239291      seattle
2021-06-18 19:09:13.798239       0.009752       0.104627      newyork
2021-06-18 19:09:13.805747       0.009856       0.104453      newyork
2021-06-18 19:09:13.808032       0.011153       0.106124      chicago
2021-06-18 19:09:13.809929       0.009975       0.104392      newyork

                           client_city        function_name  \
time
2021-06-18 18:59:04.529156     newyork   resnet50-inference
2021-06-18 18:59:04.539533     newyork  mobilenet-inference
2021-06-18 18:59:04.568010     newyork   resnet50-inference
2021-06-18 18:59:04.611242     newyork  mobilenet-inference
2021-06-18 18:59:04.653844     chicago     speech-inference
...                                ...                  ...
2021-06-18 19:09:13.779441     newyork  mobilenet-inference
2021-06-18 19:09:13.798239     chicago     speech-inference
2021-06-18 19:09:13.805747     chicago   resnet50-inference
2021-06-18 19:09:13.808032     newyork     speech-inference
2021-06-18 19:09:13.809929     chicago     speech-inference

                                                       function_image  \
time
2021-06-18 18:59:04.529156        faas-workloads/resnet-inference-gpu
2021-06-18 18:59:04.539533     faas-workloads/mobilenet-inference-tpu
2021-06-18 18:59:04.568010        faas-workloads/resnet-inference-gpu
2021-06-18 18:59:04.611242     faas-workloads/mobilenet-inference-tpu
2021-06-18 18:59:04.653844     faas-workloads/speech-inference-tflite
...                                                               ...
2021-06-18 19:09:13.779441  faas-workloads/mobilenet-inference-tflite
2021-06-18 19:09:13.798239     faas-workloads/speech-inference-tflite
2021-06-18 19:09:13.805747        faas-workloads/resnet-inference-gpu
2021-06-18 19:09:13.808032     faas-workloads/speech-inference-tflite
2021-06-18 19:09:13.809929     faas-workloads/speech-inference-tflite

                                  node       replica_id
time
2021-06-18 18:59:04.529156        nx_0  140049108402704
2021-06-18 18:59:04.539533     coral_1  140049134546512
2021-06-18 18:59:04.568010        nx_0  140049108402704
2021-06-18 18:59:04.611242     coral_1  140049134546512
2021-06-18 18:59:04.653844       nx_16  140049108207120
...                                ...              ...
2021-06-18 19:09:13.779441  xeoncpu_94  140049106642832
2021-06-18 19:09:13.798239     rpi3_77  140049106641360
2021-06-18 19:09:13.805747       tx2_7  140048980545168
2021-06-18 19:09:13.808032      rpi4_0  140049106493904
2021-06-18 19:09:13.809929   rockpi_12  140049106643152

[30996 rows x 14 columns]
30996

,name,total,nyc_rep,nyc_client,chg_rep,chg_client,sea_rep,sea_client
0,Round Robin centralized,45869,13127,19405,16445,13185,16297,13279
1,Least Response Time centralized,45888,5855,19414,39052,13188,981,13286
2,Round Robin on all nodes,45695,12660,19331,16745,13140,16290,13224
3,Least Response Time on all nodes,46002,8123,19470,23690,13218,14189,13314

In [38]:
import pandas as pd
pd.set_option('display.max_rows', 500)
print(results[0].experiment.name)
# results[3].function_deployment['node'].unique()
s = results[3].schedule
s[s['successful'] == True].count()

Round Robin centralized

value            594
function_name    594
image            594
replica_id       594
node_name        594
successful       594
dtype: int64